# Generated by Django 3.1.1 on 2020-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetToPostRequestMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('trigger_action', models.CharField(max_length=50)),
                ('trigger_key', models.CharField(max_length=50)),
            ],
        ),
    ]
